# Generated by Django 4.2.2 on 2023-06-28 10:37

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('diretor_a', models.CharField(max_length=100, null=True)),
                ('diretores_ass', models.CharField(max_length=200, null=True)),
                ('secretarios', models.CharField(max_length=100, null=True)),
                ('tesoureiro', models.CharField(max_length=100, null=True)),
                ('primeiro_anciao', models.BooleanField(default=False, null=True)),
                ('id_membro', models.ForeignKey(null=True, on_delete=django.db.models.fields.NOT_PROVIDED, to='comissao.membros')),
            ],
        ),
    ]
