# Generated by Django 4.2.2 on 2023-06-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargos',
            name='diretores_ass',
        ),
        migrations.RemoveField(
            model_name='cargos',
            name='secretarios',
        ),
        migrations.RemoveField(
            model_name='cargos',
            name='tesoureiro',
        ),
        migrations.AddField(
            model_name='cargos',
            name='anciao_jovem',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='cargos',
            name='coordenador_a',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='cargos',
            name='diaconisa',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='cargos',
            name='diaconisa_chefe',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='cargos',
            name='diacono',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='cargos',
            name='diacono_chefe',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='cargos',
            name='diretor_a_ass',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='cargos',
            name='diretor_assistente',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='cargos',
            name='diretor_sonoplastia',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='cargos',
            name='professor_a',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='cargos',
            name='secretario_a',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='cargos',
            name='secretario_a_ass',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='cargos',
            name='tesoureiro_a',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cargos',
            name='diretor_a',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
