# Generated by Django 4.2.2 on 2023-09-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0002_remove_cargos_diretores_ass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membros',
            name='apto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membros',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
