# Generated by Django 4.2.2 on 2023-10-03 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0003_membros_apto_membros_ativo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cargos',
            new_name='MembroCargos',
        ),
    ]
