# Generated by Django 4.2.2 on 2023-10-03 13:52

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0004_rename_cargos_membrocargos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membrocargos',
            name='anciao_jovem',
        ),
        migrations.RemoveField(
            model_name='membrocargos',
            name='coordenador_a',
        ),
        migrations.RemoveField(
            model_name='membrocargos',
            name='diaconisa',
        ),
        migrations.RemoveField(
            model_name='membrocargos',
            name='diaconisa_chefe',
        ),
        migrations.RemoveField(
            model_name='membrocargos',
            name='diacono',
        ),
        migrations.RemoveField(
            model_name='membrocargos',
            name='diacono_chefe',
        ),
        migrations.RemoveField(
            model_name='membrocargos',
            name='diretor_a',
        ),
        migrations.RemoveField(
            model_name='membrocargos',
            name='diretor_a_ass',
        ),
        migrations.RemoveField(
            model_name='membrocargos',
            name='diretor_assistente',
        ),
        migrations.RemoveField(
            model_name='membrocargos',
            name='diretor_sonoplastia',
        ),
        migrations.RemoveField(
            model_name='membrocargos',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='membrocargos',
            name='primeiro_anciao',
        ),
        migrations.RemoveField(
            model_name='membrocargos',
            name='professor_a',
        ),
        migrations.RemoveField(
            model_name='membrocargos',
            name='secretario_a',
        ),
        migrations.RemoveField(
            model_name='membrocargos',
            name='secretario_a_ass',
        ),
        migrations.RemoveField(
            model_name='membrocargos',
            name='tesoureiro_a',
        ),
        migrations.AddField(
            model_name='membrocargos',
            name='id_cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.NOT_PROVIDED, to='comissao.listacargos'),
        ),
    ]
