# Generated by Django 4.2.2 on 2023-10-05 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0006_listaindicados_votacao_delete_membrocargos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votacao',
            name='id_cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comissao.listacargos'),
        ),
    ]
