# Generated by Django 4.2.2 on 2023-10-05 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0008_votacao_finalizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaindicados',
            name='id_membro',
        ),
        migrations.AddField(
            model_name='listaindicados',
            name='id_membro_indicado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Membro_Indicado', to='comissao.membros'),
        ),
        migrations.AddField(
            model_name='listaindicados',
            name='id_membro_votou',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Membro_Votou', to='comissao.membros'),
        ),
        migrations.AddField(
            model_name='votacao',
            name='indicacao',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
